---
- name: Configure Remote Desktop Services.
  ansible.windows.win_regedit:
    path: "{{ item }}"
    name: fDenyTSConnections
    data: 0x00000000
    type: dword
    state: "{{ 'present' if remote_desktop_enabled else 'absent' }}"
  loop:
    - "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\"
    - "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services"

- name: Configure Firewall rules (RDS).
  ansible.windows.win_shell: >
    "{{ 'Enable-NetFirewallRule' if remote_desktop_enabled else 'Disable-NetFirewallRule' }}
    -DisplayGroup 'Remotedesktop'"
